export const months = {
  0: 'January',
  1: 'February',
  2: 'March',
  3: 'April',
  4: 'May',
  5: 'June',
  6: 'July',
  7: 'August',
  8: 'September',
  9: 'October',
  10: 'November',
  11: 'December'
}

export const days = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday'
]

export const icon = {
  "Sunny": "far fa-sun",
  "Mostly sunny": "far fa-sun",
  "Partly sunny": "fas fa-cloud-sun",
  "Hazy sunshine": "fas fa-cloud-sun",
  "Mostly sloudy": "fas fa-cloud",
  "Cloudy": "fas fa-cloud",
  "Dreary": "fas fa-smog",
  "Fog": "fas fa-smog",
  "Showers": "far fas fa-cloud-showers-heavy",
  "Mostly cloudy w/ showers": "fas fa-cloud-showers-heavy",
  "Partly sunny w/ showers": "fas fa-cloud-sun-rain",
  "T-Storms": "fas fa-cloud-showers-heavy",
  "Partly sunny w/ T-Storms": "fas fa-cloud-sun-rain",
  "Rain": "fas fa-cloud-showers-heavy",
  "Flurries": "fas fa-cloud-showers-heavy",
  "Partly sunny w/ Flurries": "fas fa-cloud-sun-rain",
  "Snow": "far fa-snowflake",
  "Ice": "far fa-snowflake",
  "Sleet": "far fa-wind",
  "Freezing rain": "fas fa-temperature-low",
  "Rain and snow": "far fa-snowflake",
  "Hot": "fas fa-temperature-high",
  "Cold": "fas fa-temperature-low",
  "Windy": "fas fa-wind",
  "Clear": "far fa-umbrella",
  "Mostly clear": "far fa-umbrella",
  "Partly cloudy": "fas fa-cloud",
  "Intermittent clouds": "fas fa-cloud",
  "Hazy moonlight": "fas fa-moon",
  "Mostly cloudy": "fas fa-cloud",
  "Partly cloudy w/ Showers": "fas fa-cloud-showers-heavy",
  "Mostly cloudy w/ Showers": "fas fa-cloud-showers-heavy",
  "Partly cloudy w/ T-Storms": "fas fa-poo-storm",
  "Mostly cloudy w/ T-Storms": "fas fa-poo-storm",
  "Mostly cloudy w/ Flurries": "fas fa-poo-storm",
  "Mostly cloudy w/ Snow": "far fa-snowflake",
};