export const months = {
  0: 'January',
  1: 'February',
  2: 'March',
  3: 'April',
  4: 'May',
  5: 'June',
  6: 'July',
  7: 'August',
  8: 'September',
  9: 'October',
  10: 'November',
  11: 'December'
}

export const days = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday'
]

export const icon = {
  "Sunny": "far fa-sun",
  "Mostly sunny": "far fa-sun",
  "Partly sunny": "fas fa-cloud-sun",
  "Intermittent clouds": "fas fa-cloud",
  "Hazy sunshine": "far fa-sun",
  "Mostly sloudy": "far fa-cloud",
  "Cloudy": "far fa-cloud",
  "Dreary": "far fa-cloud",
  "Fog": "far fa-cloud",
  "Showers": "far fas fa-cloud-showers-heavy",
  "Mostly sloudy w/ showers": "fas fa-cloud-showers-heavy",
  "Partly sunny w/ showers": "far fa-sun",
  "T-Storms": "fas fa-cloud-showers-heavy",
  "Mostly sloudy w/ T-Storms": "fas fa-cloud-showers-heavy",
  "Partly Sunny w/ T-Storms": "fas fa-cloud-showers-heavy",
  "Rain": "fas fa-cloud-showers-heavy",
  "Flurries": "fas fa-cloud-showers-heavy",
  "Mostly Cloudy w/ Flurries": "fas fa-cloud-showers-heavy",
  "Partly Sunny w/ Flurries": "far fa-sun",
  "Snow": "far fa-snowflake",
  "Mostly Cloudy w/ Snow": "far fa-snowflake",
  "Ice": "far fa-snowflake",
  "Sleet": "far fa-snowflake",
  "Freezing Rain": "far fa-snowflake",
  "Rain and Snow": "far fa-snowflake",
  "Hot": "far fa-sun",
  "Cold": "far fa-sun",
  "Windy": "far fa-smog",
  "Clear": "far fa-sun",
  "Mostly Clear": "far fa-sun",
  "Partly Cloudy": "far fa-snowflake",
  "Intermittent Clouds": "far fa-snowflake",
  "Hazy Moonlight": "far fa-sun",
  "Mostly Cloudy": "far fa-sun",
  "Partly Cloudy w/ Showers": "far fa-smog",
  "Mostly Cloudy w/ Showers": "far fa-smog",
  "Partly Cloudy w/ T-Storms": "far fa-sun",
  "Mostly Cloudy w/ T-Storms": "far fa-sun",
  "Mostly Cloudy w/ Flurries": "far fa-sun",
  "Mostly Cloudy w/ Snow": "far fa-sun",
};